baseURL: "https://its-rajesh.github.io/rajesh/"
title: Rajesh Rameshbabu
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        #- name: Courses
        #  url: courses/
        #  weight: 3
        - name: Others
          url: others/
          weight: 4 
        - name: Blog
          url: https://its-rajesh.github.io/dharmicwaves/
          weight: 6

params:
    description: "This website hosts Rajesh's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Rajesh R
    googleAnalyticsID: "G-0XGK1HR32V"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","projects","others"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Rajesh Rameshbabu
          subtitle: "I am a PhD scholar in the Listening Technology Lab at the University of Illinois Chicago, USA, working under the supervision of Prof. Ryan Corey. My research focuses on audio signal processing, machine learning, and deep learning. I earned my MS by Research from IIT Mandi, India, with a reseach focus on interference reduction and source separation."
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            #- name: Books
            #  url: books/
            #- name: Courses
            #  url: courses/
            #- name: Tags
            #  url: tags/
            - name: Others
              url: others/
            - name: Blog
              url: https://its-rajesh.github.io/dharmicwaves/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:rajeshr12@zohomail.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/rajeshrrajeshr/
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=QOwRUvMAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/its-rajesh
        - name: Instagram
          url: https://www.instagram.com/waveandmind/
        - name: Twitter
          url: https://x.com/Rajesh_smartino
        

    assets:
        disableScrollBarStyle: true
        css:
          - "css/timeline.css"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Rajesh Rameshbabu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
